### ISSUE TITLE
录制下来的视频无法播放

### ISSUE THREAD

**Issue by subdance** [alo7/rebirth#13]
为了能够自动启动录制，在chrome_extension目录下加了如下代码
`(window as MyWindow & typeof globalThis).rebirth.start();
setTimeout(function() {
  (window as MyWindow & typeof globalThis).rebirth.stop('testing file');
}, 1000 * 60);`
执行`npm run build`更新dist文件夹下的脚本后，进行录制。得到了视频文件，但是打开之后进度条显示时长为0，并且无法播放，文件本身也很小（4kb）
请问是哪里出错了吗

**Comment by BlackHole1** [comment]
长度为0是 `chrome` 录制 `webm` 的问题，目前 `chrome` 不认为这是一个bug，故没有修复，不过可以对 `webm` 进行 `ffmpeg` 二次转码就可以解决这个问题。

不过大小为 4kb，确实有点问题。可以提供你的测试demo repo以及你的录制地址么，我在本地进行复现。

**Comment by subdance** [comment]
@BlackHole1 
https://github.com/subdance/rebirth-master
仓库地址，只是如issue中更改了injected.ts的内容并重新build。

**Comment by BlackHole1** [comment]
@subdance 要录制的地址是随便都行是么

**Comment by subdance** [comment]
@BlackHole1 就用你rebirth demo的地址吧，我当时用的就是这个

**Comment by BlackHole1** [comment]
你是在本地直接运行的么？还是说打包成一个docker镜像，在docker里进行运行

**Comment by subdance** [comment]
@BlackHole1 在docker里运行的。

**Comment by BlackHole1** [comment]
那我是否可以理解成，你的docker 运行代码为：

Dockerfile:
```Dockerfile
FROM alo7docker/rebirth
```

docker-compose.yml:
```yml
version: '3'
services:
  test_rebirth:
    build: .
    container_name: test_rebirth
    ports:
     - "9223"
     - "5920"
    volumes:
      - ./rebirth_data/video:/root/Downloads
      - ./rebirth_data/logs:/etc/www/logs
      - ./src/extensions_dist:/etc/www/extensions_dist
    environment:
      MATERIAL_URL: "https://www.bugs.cc/self_page/github/rebirth/webm2mp4/"
      START_VNC: "yes"
```
